#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════
#  VPS Control App - One-Click Deploy Script
#  Detects Traefik, generates secrets, deploys.
# ═══════════════════════════════════════════════════

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════╗"
echo "║     VPS Control App - Deploy Script      ║"
echo "╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ─── [1/6] Check prerequisites ───
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"

if ! command -v docker &>/dev/null; then
  echo -e "${RED}ERROR: Docker is not installed.${NC}"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo -e "${RED}ERROR: Docker Compose V2 is not available.${NC}"
  exit 1
fi

if ! command -v openssl &>/dev/null; then
  echo -e "${RED}ERROR: openssl is required to generate secrets.${NC}"
  exit 1
fi

echo -e "${GREEN}  ✓ Docker, Docker Compose, and openssl found.${NC}"

# ─── [2/6] Detect Traefik network ───
echo -e "${YELLOW}[2/6] Detecting Traefik network...${NC}"

TRAEFIK_NETWORK=""

# Try common Traefik network names
for net in traefik proxy web traefik-public traefik_default; do
  if docker network inspect "$net" &>/dev/null; then
    TRAEFIK_NETWORK="$net"
    break
  fi
done

if [ -z "$TRAEFIK_NETWORK" ]; then
  echo -e "${RED}  ✗ No Traefik network detected automatically.${NC}"
  echo "    Available Docker networks:"
  docker network ls --format "    - {{.Name}}" | grep -v "bridge\|host\|none"
  echo ""
  read -rp "  Enter the Traefik network name: " TRAEFIK_NETWORK

  if ! docker network inspect "$TRAEFIK_NETWORK" &>/dev/null; then
    echo -e "${RED}ERROR: Network '${TRAEFIK_NETWORK}' does not exist.${NC}"
    exit 1
  fi
fi

echo -e "${GREEN}  ✓ Using Traefik network: ${TRAEFIK_NETWORK}${NC}"

# ─── [3/6] Collect configuration ───
echo -e "${YELLOW}[3/6] Configuration...${NC}"

read -rp "  Enter domain (e.g. vps.example.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  echo -e "${RED}ERROR: Domain is required.${NC}"
  exit 1
fi

read -rp "  Enter Traefik cert resolver [letsencrypt]: " CERT_RESOLVER
CERT_RESOLVER="${CERT_RESOLVER:-letsencrypt}"

read -rp "  Enter admin username [admin]: " ADMIN_USERNAME
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

read -rsp "  Enter admin password: " ADMIN_PASSWORD
echo ""
if [ -z "$ADMIN_PASSWORD" ]; then
  echo -e "${RED}ERROR: Admin password is required.${NC}"
  exit 1
fi

echo -e "${GREEN}  ✓ Domain:        ${DOMAIN}${NC}"
echo -e "${GREEN}  ✓ Cert resolver: ${CERT_RESOLVER}${NC}"
echo -e "${GREEN}  ✓ Admin user:    ${ADMIN_USERNAME}${NC}"

# ─── [4/6] Generate cryptographic secrets ───
echo -e "${YELLOW}[4/6] Generating secrets...${NC}"

DB_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

echo -e "${GREEN}  ✓ Database password generated (48 hex chars).${NC}"
echo -e "${GREEN}  ✓ JWT secret generated (64 hex chars).${NC}"
echo -e "${GREEN}  ✓ AES-256-GCM encryption key generated (64 hex chars).${NC}"

# ─── [5/6] Write .env file ───
echo -e "${YELLOW}[5/6] Writing .env file...${NC}"

if [ -f .env ]; then
  cp .env ".env.backup.$(date +%s)"
  echo -e "${YELLOW}  ! Existing .env backed up.${NC}"
fi

cat > .env << ENVFILE
# ═══════════════════════════════════════════════════
#  VPS Control App - Environment Configuration
#  Generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#  DO NOT commit this file to version control.
# ═══════════════════════════════════════════════════

# ─── Domain & Traefik ───
DOMAIN=${DOMAIN}
CERT_RESOLVER=${CERT_RESOLVER}
TRAEFIK_NETWORK=${TRAEFIK_NETWORK}

# ─── Database ───
DB_HOST=db
DB_PORT=5432
DB_NAME=vpscontrol
DB_USER=vpscontrol
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://vpscontrol:${DB_PASSWORD}@db:5432/vpscontrol?schema=public

# ─── Security ───
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ─── Admin Account ───
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ENVFILE

echo -e "${GREEN}  ✓ .env file created.${NC}"

# ─── [6/6] Build and deploy ───
echo -e "${YELLOW}[6/6] Building and starting containers...${NC}"
echo "    This may take a few minutes on first run."
echo ""

docker compose up -d --build

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗"
echo -e "║         Deployment Complete!                 ║"
echo -e "╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  URL:      https://${DOMAIN}"
echo -e "  Admin:    ${ADMIN_USERNAME}"
echo -e "  Network:  ${TRAEFIK_NETWORK}"
echo ""
echo -e "${YELLOW}  Notes:${NC}"
echo -e "  - SSL certificate may take a moment to provision via ${CERT_RESOLVER}."
echo -e "  - View logs:    docker compose logs -f"
echo -e "  - Stop:         docker compose down"
echo -e "  - DB backups:   docker compose exec db pg_dump -U vpscontrol vpscontrol"
echo ""
